baseURL = "https://chenwang.org/"
languageCode = "en-gb"
title = "Thoughts from Chen W"
theme = "paperback"

[params]

MainSections = "post"

AuthorName = "Chen W"

Tagline = ""

HomepagePosts = 3

GithubUsername = "cwang"

TwitterUsername = "cwang"

LinkedInUsername = "chenwang"